# application-test.yml
server:
  port: 9999
  tomcat:
    threads:
      max: 50
      min-spare: 5
    max-connections: 2000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30 # 心跳间隔，默认 30 秒
    lease-expiration-duration-in-seconds: 90 # 服务失效时间，默认 90 秒
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    region: default
    availability-zones:
      default: defaultZone
    prefer-same-zone-eureka: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${tjtc.eureka.host}:${tjtc.eureka.port}/eureka/
    registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true

spring:
  application:
    name: dmp-gateway
  cloud:
    service-registry:
      auto-registration:
        enabled: true
    gateway:
      routes:
        - id: global-options
          uri: no://op
          predicates:
            - Path=/dmp/**
            - Method=OPTIONS
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, *
            - AddResponseHeader=Access-Control-Allow-Methods, GET,POST,OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, *

        - id: login
          uri: lb://dmp-security
          predicates:
            - Path=/dmp/login
            - Header=app, (TROLLEYTRACE|GPS|CATALOGUE|PINPOINT|DMPCLIENT)
            - Method=GET,POST
          filters:
            - RewritePath=/dmp/login, /dmp/security/identity/login
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
        
        - id: logout
          uri: lb://dmp-security
          predicates:
            - Path=/dmp/logout
            - Header=app, DMPCLIENT
            - Method=GET,POST
          filters:
            - RewritePath=/dmp/logout, /dmp/security/identity/logout
            - name: AuthorityValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: authority-internal
          uri: lb://dmp-authority
          predicates:
            - Path=/dmp/authority/**
            - Header=app, (TROLLEYTRACE|GPS|CATALOGUE|PINPOINT|DMPCLIENT)
            - Method=GET,POST
          filters:
            - name: InternalAccessValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: security-client
          uri: lb://dmp-security
          predicates:
            - Path=/dmp/security/**
            - Header=app,DMPCLIENT
            - Method=GET,POST
          filters:
            - name: AuthorityValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: message-device
          uri: lb://dmp-message
          predicates:
            - Path=/dmp/message/device/**
            - Header=app, (TROLLEYTRACE|GPSREPLY|CATALOGUE|PINPOINT)
            - Method=GET,POST
          filters:
            - name: DeviceValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                exceptions: java.net.ConnectException, java.io.IOException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: message-client
          uri: lb://dmp-message
          predicates:
            - Path=/dmp/message/client/**
            - Header=app,DMPCLIENT
            - Method=GET,POST
          filters:
            - name: AuthorityValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                exceptions: java.net.ConnectException, java.io.IOException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: gps-device
          uri: lb://dmp-gps
          predicates:
            - Path=/dmp/gps/device/**
            - Header=app,GPS
            - Method=GET,POST
          filters:
            - name: DeviceValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                exceptions: java.net.ConnectException, java.io.IOException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: gps-client
          uri: lb://dmp-gps
          predicates:
            - Path=/dmp/gps/client/**
            - Header=app,DMPCLIENT
            - Method=GET,POST
          filters:
            - name: AuthorityValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                exceptions: java.net.ConnectException, java.io.IOException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: transit-device
          uri: lb://dmp-transit
          predicates:
            - Path=/dmp/transit/device/**
            - Header=app,TROLLEYTRACE
            - Method=GET,POST
          filters:
            - name: DeviceValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                exceptions: java.net.ConnectException, java.io.IOException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: transit-client
          uri: lb://dmp-transit
          predicates:
            - Path=/dmp/transit/client/**
            - Header=app,DMPCLIENT
            - Method=GET,POST
          filters:
            - name: AuthorityValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                exceptions: java.net.ConnectException, java.io.IOException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: beacon-device
          uri: lb://dmp-beacon
          predicates:
            - Path=/dmp/beacon/device/**
            - Header=app, (TROLLEYTRACE|PINPOINT)
            - Method=GET,POST
          filters:
            - name: DeviceValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                exceptions: java.net.ConnectException, java.io.IOException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: beacon-client
          uri: lb://dmp-beacon
          predicates:
            - Path=/dmp/beacon/client/**
            - Header=app,DMPCLIENT
            - Method=GET,POST
          filters:
            - name: AuthorityValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                exceptions: java.net.ConnectException, java.io.IOException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: config-client
          uri: lb://dmp-config-center
          predicates:
            - Path=/dmp/app/config/client/**
            - Header=app,DMPCLIENT
            - Method=GET,POST
          filters:
            - name: AuthorityValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                exceptions: java.net.ConnectException, java.io.IOException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

        - id: catalogue-client
          uri: lb://dmp-catalogue
          predicates:
            - Path=/dmp/catalogue/client/**
            - Header=app,DMPCLIENT
            - Method=GET,POST
          filters:
            - name: AuthorityValidation
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                exceptions: java.net.ConnectException, java.io.IOException
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:9999"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "app"
              - "client"
              - "account"
              - "timestamp"
              - "digest"
              - "sign"
              - "*"
            exposedHeaders:
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 6000 # 连接超时
        response-timeout: 6s # 响应超时
  security:
    user:
      name: wis
      password: wIsdom2019!

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus,loggers"  # 只暴露必要端点
      base-path: /actuator  # 明确设置基础路径
  info:
    git:
      mode: full
  health:
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED  # 只向授权用户显示详情
    shutdown:
      access: NONE  # 禁用远程关闭功能

tjtc:
  date-format: yyyy-MM-dd
  date-time-format: yyyy-MM-dd HH:mm:ss
  default-password: 123456
  debug: false
  device:
    token: tjtc
  eureka:
    host: localhost
    port: 8001

  authority:
    login: http://dmp-authority/dmp/authority/sign/validate-login
    api: http://dmp-authority/dmp/authority/sign/validate-api
    multipart: http://dmp-authority/dmp/authority/sign/validate-multipart
    upload-path: /packet/file/upload